version: "3.7"
services:
  nocraft:
    build:
      context: ./nocraft-rest
    image: dzmitryitechart/nocraft-server:local
    container_name: nocraft
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:19080:19080
    environment:
      - server.port=9080
      - image.path=https://picsum.photos/300
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=19080"
      - keycloak.auth-server-url=http://keycloak:8080/auth
