version: "3.7"
services:
  nocraft:
    build:
      context: .
      dockerfile: nocraft-rest/Dockerfile
    image: dzmitryitechart/nocraft-server:0.17-nosec
    container_name: nocraft
    volumes:
      - ${GIT_KEYPATH}:/root/.ssh/github
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:19080:19080
    environment:
      - keycloak.auth-server-url=http://keycloak:8080/auth
      - server.port=9080
      - logging.level.root=INFO
      - froala.git.username=${GIT_USER}
      - froala.git.key-path=/root/.ssh/github
      - froala.git.key-password=${GIT_KEYPASSWORD}
      - froala.git.repository=${GIT_SSH_REPO}
      - froala.ui.url=http://localhost:4201
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:19080"
