version: "3.7"
services:
  nocraft:
    build:
      context: .
      dockerfile: nocraft-rest/Dockerfile
    image: dzmitryitechart/nocraft-server:local
    container_name: nocraft
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:19080:19080
    environment:
      - keycloak.auth-server-url=http://keycloak:8080/auth
      - server.port=9080
      - logging.level.root=INFO
      - froala.git.username=${GIT_USER}
      - froala.git.token=${GIT_TOKEN}
      - froala.git.repository=${GIT_REPO}
      - froala.ui.url=http://dev:4201
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=19080"
