version: "3.7"
services:
  nocraft:
    build:
      context: .
    image: dzmitryitechart/nocraft-server:local
    container_name: nocraft
    ports:
      - 9080:9080
    environment:
      - server.port=9080
      - image.path=https://picsum.photos/300