server:
  port: 9080

keycloak:
  realm: "Demo"
  bearer-only: true
  auth-server-url: "http://keycloak:8080/auth/"
  ssl-required: "external"
  resource: "server-bearer-only"
  confidential-port: 0


image.path: "https://picsum.photos/200"

